apiVersion: apps/v1
kind: Deployment
metadata:
  name:  python-deployment
  namespace: apps-ns
  labels:
    app:  pythonapp
spec:
  selector:
    matchLabels:
      app: pythonapp
  replicas: 1
  template:
    metadata:
      labels:
        app:  pythonapp
    spec:
      containers:
      - name:  python-container
        image:  belalhany/python_app:${BUILDRUN_HASH}
        ports:
        - containerPort:  80
          name:  http
        - containerPort: 8000
        


