apiVersion: apps/v1
kind: Deployment
metadata:
  name:  python-deployment
  labels:
    app:  pythonapp
spec:
  selector:
    matchLabels:
      app: pythonapp
  replicas: 1
  template:
    metadata:
      labels:
        app:  pythonapp
    spec:
      containers:
      - name:  python-container
        image:  belalhany/python_app:${BUILDRUN_HASH}
        ports:
        - containerPort:  80
          name:  http
        - containerPort: 8000
        
---

apiVersion: v1
kind: Service
metadata:
  name: lb-service-app
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"  
spec:
  selector:
    app: pythonapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000


